# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='drone_ssid',
            field=models.CharField(max_length=200),
        ),
    ]
